/* eslint-disable max-len */

import { Tags } from '@/tag';

export type AiAutoGeneratedField =
  'title' |
  'caption' |
  'tags' |
  'semantic'

export const AI_AUTO_GENERATED_FIELDS_ALL: AiAutoGeneratedField[] = [
  'title',
  'caption',
  'tags',
  'semantic',
];

export const AI_AUTO_GENERATED_FIELDS_DEFAULT: AiAutoGeneratedField[] = [
  'title',
  'tags',
  'semantic',
];

export const parseAiAutoGeneratedFieldsString = (
  text = AI_AUTO_GENERATED_FIELDS_DEFAULT.join(','),
): AiAutoGeneratedField[] => {
  const textFormatted = text.trim().toLocaleLowerCase();
  if (textFormatted === 'none') {
    return [];
  } else if (textFormatted === 'all') {
    return AI_AUTO_GENERATED_FIELDS_ALL;
  } else {
    const fields = textFormatted
      .toLocaleLowerCase()
      .split(',')
      .map(field => field.trim())
      .filter(field => AI_AUTO_GENERATED_FIELDS_ALL
        .includes(field as AiAutoGeneratedField));
    return fields as AiAutoGeneratedField[];
  }
};

export type AiImageQuery =
  'title' |
  'caption' |
  'title-and-caption' |
  'tags' |
  'description-small' |
  'description' |
  'description-large' |
  'description-semantic';

export const getAiImageQuery = (
  query: AiImageQuery,
  existingTags: Tags = [],
): string => {
  switch (query) {
  case 'title': return '为这张照片写一个引人注目的标题(6个字以内),直接返回标题';
  case 'caption': return '为这张照片写一个简洁的说明文字(10个字以内,不带标点符号),直接返回说明';
  case 'title-and-caption': return '为这张照片写一个引人注目的标题和简洁的说明文字(总共18个字以内),使用格式 Title: "标题" Caption: "说明"';
  case 'tags':
    const tagQuery = '请用1到2个独特的关键词描述这张图片，用中文逗号,分隔。避免使用“自然”、“旅行”、“建筑”或“天空”等泛泛的词语，不要使用形容词或副词。请使用对图像具有高度针对性的术语，避免重复。';
    const tags = existingTags.map(({ tag }) => tag).join(', ');
    return tags
      ? `${tagQuery}. 考虑使用这些现有的标签，但前提是它们与图像相关。: ${tags}.`
      : tagQuery;
  case 'description-small': return '简明扼要地描述这张照片(不要以"这张照片显示"或"这是一张...的照片"开头)，直接返回描述';
  case 'description': return '描述这张图片';
  case 'description-large': return '详细描述这张图片';
  case 'description-semantic': return '以英文逗号,分隔的列表形式列出这张图片中的最多5个事物(不带描述),直接返回';
  }
};

export const parseTitleAndCaption = (text: string) => {
  const matches = text.includes('Title')
    ? text.match(/^[`'"]*Title: ["']*(.*?)["']*[ ]*Caption: ["']*(.*?)\.*["']*[`'"]*$/)
    : text.match(/^(.*?): (.*?)$/);

  return {
    title: matches?.[1] ?? '',
    caption: matches?.[2] ?? '',
  };
};

export const cleanUpAiTextResponse = (text: string) =>
  text
    .replaceAll('\n', ' ')
    .replaceAll('"', '')
    .replace(/\.$/, '');
