/* eslint-disable max-len */

import { Tags } from '@/tag';

export type AiAutoGeneratedField =
  'title' |
  'caption' |
  'tags' |
  'semantic'

export const AI_AUTO_GENERATED_FIELDS_ALL: AiAutoGeneratedField[] = [
  'title',
  'caption',
  'tags',
  'semantic',
];

export const AI_AUTO_GENERATED_FIELDS_DEFAULT: AiAutoGeneratedField[] = [
  'title',
  'tags',
  'semantic',
];

export const parseAiAutoGeneratedFieldsString = (
  text = AI_AUTO_GENERATED_FIELDS_DEFAULT.join(','),
): AiAutoGeneratedField[] => {
  const textFormatted = text.trim().toLocaleLowerCase();
  if (textFormatted === 'none') {
    return [];
  } else if (textFormatted === 'all') {
    return AI_AUTO_GENERATED_FIELDS_ALL;
  } else {
    const fields = textFormatted
      .toLocaleLowerCase()
      .split(',')
      .map(field => field.trim())
      .filter(field => AI_AUTO_GENERATED_FIELDS_ALL
        .includes(field as AiAutoGeneratedField));
    return fields as AiAutoGeneratedField[];
  }
};

export type AiImageQuery =
  'title' |
  'caption' |
  'title-and-caption' |
  'tags' |
  'description-small' |
  'description' |
  'description-large' |
  'description-semantic';


export const getAiImageQuery = (
  query: AiImageQuery,
  existingTags: Tags = [],
  existingTitle?: string,
): string => {
  switch (query) {  
  case 'title': return '为这张图片写一个有吸引力的标题，尽量简短（不超过3个词）';
  case 'caption': return existingTitle
    ? `为这张图片写一句简洁有力的说明文字，不超过6个词，不要使用标点符号，并与现有标题相呼应："${existingTitle}"`
    : '为这张图片写一句简洁有力的说明文字，不超过6个词，不要使用标点符号';
  case 'title-and-caption': return '为这张图片分别写一个有吸引力的标题和简洁的说明，总长度不超过8个词。使用以下格式输出：Title: "title" Caption: "caption"';
  case 'tags':
    const tagQuery = '用1-2个以逗号分隔的唯一关键词描述这张图片，不要使用形容词或副词。避免使用诸如“nature”“travel”“architecture”“sky”等泛泛的词。使用对图片高度具体且不冗余的词。';
    const tags = existingTags.map(({ tag }) => tag).join(', ');
    return tags
      ? `${tagQuery} 可以参考这些已有标签，但仅在相关时使用：${tags}。`
      : tagQuery;
  case 'description-small': return '简洁描述这张图片，不要以“这张图片展示了”或“这是一张……的照片”这样的开头';
  case 'description': return '描述这张图片';
  case 'description-large': return '详细描述这张图片';
  case 'description-semantic': return '列出这张图片中最多5个事物，不要附加说明，使用逗号分隔';
  }
};

export const parseTitleAndCaption = (text: string) => {
  const matches = text.includes('Title')
    ? text.match(/^[`'"]*Title: ["']*(.*?)["']*[ ]*Caption: ["']*(.*?)\.*["']*[`'"]*$/)
    : text.match(/^(.*?): (.*?)$/);

  return {
    title: matches?.[1] ?? '',
    caption: matches?.[2] ?? '',
  };
};

export const cleanUpAiTextResponse = (text: string) =>
  text
    .replaceAll('\n', ' ')
    .replaceAll('"', '')
    .replace(/\.$/, '');
