/* eslint-disable max-len */

import { Tags } from '@/tag';
import { parseCommaSeparatedKeyString } from '@/utility/key';
import { z } from 'zod';

export type AiAutoGeneratedField =
  'title' |
  'caption' |
  'tags' |
  'semantic'

export const AI_AUTO_GENERATED_FIELDS_ALL: AiAutoGeneratedField[] = [
  'title',
  'caption',
  'tags',
  'semantic',
];

export const AI_AUTO_GENERATED_FIELDS_DEFAULT: AiAutoGeneratedField[] = [
  'title',
  'tags',
  'semantic',
];

export const parseAiAutoGeneratedFieldsString = (
  string?: string,
) =>
  parseCommaSeparatedKeyString({
    string,
    acceptedKeys: AI_AUTO_GENERATED_FIELDS_ALL,
    defaultKeys: AI_AUTO_GENERATED_FIELDS_DEFAULT,
  });

export const getAiTextFieldsToGenerate = (
  textFieldsToGenerate: AiAutoGeneratedField[],
  excludeTitle?: boolean,
  excludeCaption?: boolean,
  excludeTags?: boolean,
  excludeSemantic?: boolean,
): AiAutoGeneratedField[] => {
  return textFieldsToGenerate.filter(field =>
    !(excludeTitle && field === 'title') &&
    !(excludeCaption && field === 'caption') &&
    !(excludeTags && field === 'tags') &&
    !(excludeSemantic && field === 'semantic'),
  );
};

export type AiImageQuery =
  'title' |
  'caption' |
  'title-and-caption' |
  'tags' |
  'semantic';


export const getAiImageQuery = (
  query: AiImageQuery,
  existingTitle?: string,
  existingTags: Tags = [],
): string => {
  switch (query) {  
    case 'title': return '为这张图片创作一个引人注目的标题，不超过 3 个词。';
    case 'caption': return existingTitle
      ? `为这张图片写一段精炼的说明文字，不超过 6 个词，无标点符号，并与现有标题相得益彰："${existingTitle}。"`
      : '为这张图片写一段精炼的说明文字，不超过 6 个词，无标点符号。';
    case 'title-and-caption': return '为这张图片创作一个引人注目的标题和精炼的说明文字，总共不超过 8 个词，使用以下格式：标题："标题内容" 说明："说明内容"。';
    case 'tags':
      const tagQuery = '请用 1–2 个以英文逗号分隔的独特中文关键词描述这张图片，不要使用形容词或副词。避免使用诸如"自然""旅行""建筑""天空"等泛泛词语。使用对图像高度具体且不重复的名词。';
      const tags = existingTags.map(({ tag }) => tag).join(', ');
      return tags
        ? `${tagQuery}可以考虑使用以下已有标签，但仅在确实相关时采用：${tags}。`
        : tagQuery;
    case 'semantic': return '简洁地描述这张图片，不要使用"这张图片展示了"或"这是一张……的图片"等开头语。';
  }
};

const getAiImageQueryForField = (
  field: AiAutoGeneratedField,
  existingTitle?: string,
  existingTags?: Tags,
) => {
  switch(field) {
    case 'title': return `TITLE: ${getAiImageQuery('title', existingTitle, existingTags)}`;
    case 'caption': return `CAPTION: ${getAiImageQuery('caption', existingTitle, existingTags)}`;
    case 'tags': return `TAGS: ${getAiImageQuery('tags', existingTitle, existingTags)}`;
    case 'semantic': return `SEMANTIC: ${getAiImageQuery('semantic', existingTitle, existingTags)}`;
  }
};

export const getAiImageQuerySchema = (
  fields: AiAutoGeneratedField[],
  existingTitle?: string,
  existingTags?: Tags,
) => {
  const queryLines = [
    'Generate a set of meta content for the attached image:\n',
  ];

  fields.forEach(field => {
    queryLines.push(getAiImageQueryForField(field, existingTitle, existingTags));
  });

  const query = queryLines.join('\n');

  let schema = z.object();
  
  if (fields.includes('title')) {
    schema = schema.extend({ title: z.string() }); }
  if (fields.includes('caption')) {
    schema = schema.extend({ caption: z.string() }); }
  if (fields.includes('tags')) {
    schema = schema.extend({ tags: z.string() }); }
  if (fields.includes('semantic')) {
    schema = schema.extend({ semantic: z.string() }); }

  return {
    query,
    schema,
  };
};

export const parseTitleAndCaption = (text: string) => {
  const matches = text.includes('Title')
    ? text.match(/^[`'"]*Title: ["']*(.*?)["']*[ ]*Caption: ["']*(.*?)\.*["']*[`'"]*$/)
    : text.match(/^(.*?): (.*?)$/);

  return {
    title: matches?.[1] ?? '',
    caption: matches?.[2] ?? '',
  };
};

export const cleanUpAiTextResponse = (text: string) =>
  text
    .replaceAll('\n', ' ')
    .replaceAll('"', '')
    .replaceAll('**', '')
    .replaceAll('`', '')
    .replace(/\.$/, '');
